# Generated by Django 4.2.4 on 2023-08-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='rout',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='rout',
            new_name='route',
        ),
    ]
